name: Rays.shopping-mall.CI/CD

on:
  push:
    branches: ['test']
  pull_request:
    branches: ['test']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run build
      - run: cp -Rf /home/dev/rays/rays-shopping-mall/actions-runner/shopping_mall/shopping-mall/shopping-mall/dist/* /var/www/html/dist/
